apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pod-monitor-backend 
  namespace: monitoring
spec:
  selector:
    matchLabels:
      tier: backend
  namespaceSelector:
    matchNames:
    - default
  podMetricsEndpoints:
  - port: web
    path: /metrics
